# Generated by Django 5.2.1 on 2025-05-23 10:11

import django.db.models.deletion
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models

unit = ('pcs', 'kg', 'ltr', 'mtr')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]



    operations = [

        migrations.RunSQL(
            sql=f"""
            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unit') THEN
                    CREATE TYPE unit AS ENUM ({", ".join(f"'{u}'" for u in unit)});
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$ BEGIN
                IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unit') THEN
                    DROP TYPE unit;
                END IF;
            END $$;
            """
        ),
        
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('add1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('add2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('threadId', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='chatHistory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatHistory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('unit', inventory.models.PostgreSQLEnumField(default='pcs', enum_name='unit')),
                ('deleted', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.category')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('reorderLevel', models.PositiveIntegerField(default=10)),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['deleted'], name='product_deleted_63da17_idx'),
        ),
    ]
